# -*- coding: utf-8 -*-
"""Actividad6CuentasAstorga.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brrcxYJ7rd6y2KZk_FMR6J4Vp3_43ItR
"""

'''Crea una clase llamada Cuenta que tendrá los siguientes atributos: titular (que es una persona) y cantidad (puede tener decimales). 
El titular será obligatorio y la cantidad es opcional. Construye los siguientes métodos para la clase: 

Un constructor.
mostrar(): Muestra los datos de la cuenta. 
ingresar(cantidad): se ingresa una cantidad a la cuenta, si la cantidad introducida es negativa, no se hará nada. 
retirar(cantidad): se retira una cantidad a la cuenta. La cuenta puede estar en números rojos
Formato de entrega: archivo.py + link de Colab pegado en un comentario.

Hacer clic en el botón "enviar tarea" para hacer efectiva la entrega.

Fecha de entrega: hasta el 10/5 inclusive'''

class Cuenta: 

  #El constructor
  def __init__(self, titular, cantidad=0):

    #Atributos de instancia
    self.titular = titular                
    self.cantidad = cantidad

  #Métodos

  def mostrar(self):
      print("El titular de la cuenta es", self.titular,"y posee la cantidad de", self.cantidad)
       
  def ingresar(self, ingreso=0):
    if ingreso >= 0:
      self.cantidad += ingreso
      print("Despues de ingresar:", ingreso, ", su saldo es de", self.cantidad)
    else:
      print("Cantidad incorrecta")

  def retirar(self, retirar=0):
      self.cantidad -= retirar
      print("Despues de retirar:", retirar, ", su saldo es de", self.cantidad)

#Instancias

cuenta1=Cuenta("Mario")
cuenta1.mostrar()

cuenta1.ingresar(100)
cuenta1.ingresar(-100)
cuenta1.retirar(500)

cuenta2=Cuenta("Luigui", 100000)
cuenta2.mostrar()

cuenta2.ingresar(100)
cuenta2.retirar(500)